### ISSUE TITLE
Can't be used without sharkd on Ubuntu 18.04

### ISSUE THREAD

**Issue by batuhanfaik** [mbehr1/vsc-webshark#15]
`tshark` is installed and `vsc-webshark.tsharkFullPath` specifies the correct path however the plugin still asks for the `sharkd` binary

**Comment by mbehr1** [comment]
hi. is sharkd installed as well? Is it installed at the same location?
Can you paste terminal output of
```
which tshark
which sharkd
```
The readme says:
**sharkd** (and tshark) binary from Wireshark needs to be locally installed.

and
* `vsc-webshark.sharkdFullPath`: Specifies the absolute path incl filename to the sharkd binary. This needs to be set after installation.
* `vsc-webshark.tsharkFullPath`: Specifies the absolute path incl filename to the tshark binary. Defaults to 'tshark'. Needs to be set after installation if tshark is not reachable via search path.

**Comment by batuhanfaik** [comment]
The output of the terminal is
```
/usr/bin/tshark
sharkd not found
```
respectively

Since the readme said:

> With Ubuntu 20.04-LTS installing package "tshark" seems to be sufficient.

I thought `tshark` would be enough. `sharkd` is not installed, however, I couldn't find a way to install it.

**Comment by mbehr1** [comment]
How did you install Wireshark?
https://wiki.ubuntuusers.de/Wireshark/
mentions either apt install Wireshark or apt install tshark?

**Comment by batuhanfaik** [comment]
I installed both using `apt`

**Comment by mbehr1** [comment]
can you paste output of:
```
apt-cache policy wireshark
```

**Comment by batuhanfaik** [comment]
Here you go
```
❯ apt-cache policy wireshark
wireshark:
  Installed: 2.6.10-1~ubuntu18.04.0
  Candidate: 2.6.10-1~ubuntu18.04.0
  Version table:
 *** 2.6.10-1~ubuntu18.04.0 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
        100 /var/lib/dpkg/status
     2.4.5-1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

**Comment by mbehr1** [comment]
Yes, weird. sharkd seems only added to Wireshark for "focal" (ubuntu 20.04). See e.g. here: https://packages.ubuntu.com/focal/amd64/wireshark-common/filelist

So you'd need to install:
wireshark-common (3.2.3-1) [universe]
or install Wireshark from source (e.g. similar to described here: https://kifarunix.com/install-latest-wireshark-on-ubuntu-18-04/ )

**Comment by batuhanfaik** [comment]
I got it working by building from the source code of version 3.2.16 which came with `sharkd`. The latest stable version which is 3.4.8 had some issues during `cmake`. Thank you for your help!
