### ISSUE TITLE
about settings

### ISSUE THREAD

**Issue by chen-ran-mo** [mbehr1/vsc-webshark#29]
I installed the wirehark in C:\Wireshark\wireshark. But it till has the problem: Assertion Failed: argument is undefined or null. I don't know how to do it.

**Comment by mbehr1** [comment]
can you run sharkd from command line?
Search for sharkd.exe in your install folder.

**Comment by mbehr1** [comment]
(once found please post the output of
```
sharkd --version
```

**Comment by actanta** [comment]
Your work is exciting. I'd like to try your plugin.But I got the same tip.(Assertion Failed: argument is undefined or null)  

+ Here is the output of the command( `sharkd --version`).  
```
sharkd.exe --version
Sharkd (Wireshark) 4.0.6 (v4.0.6-0-gac2f5a01286a).

Copyright 1998-2023 Gerald Combs <gerald@wireshark.org> and contributors.
Licensed under the terms of the GNU General Public License (version 2 or later).
This is free software; see the file named COPYING in the distribution. There is
NO WARRANTY; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) using Microsoft Visual Studio 2022 (VC++ 14.32, build 31332),
with GLib 2.72.3, with PCRE2, with zlib 1.2.12, with Lua 5.2.4, with GnuTLS
3.6.3 and PKCS #11 support, with Gcrypt 1.10.1, with Kerberos (MIT), with
MaxMind, with nghttp2 1.46.0, with brotli, with LZ4, with Zstandard, with
Snappy, with libxml2 2.9.14, with libsmi 0.4.8, with binary plugins.

Running on 64-bit Windows 10 (22H2), build 19045, with Intel(R) Core(TM)
i7-10510U CPU @ 1.80GHz (with SSE4.2), with 16206 MB of physical memory, with
GLib 2.72.3, with PCRE2 10.40 2022-04-14, with c-ares 1.18.1, with GnuTLS 3.6.3,
with Gcrypt 1.10.1, with nghttp2 1.46.0, with brotli 1.0.9, with LZ4 1.9.3, with
Zstandard 1.5.2, with LC_TYPE=C, binary plugins supported.
```

**Comment by actanta** [comment]
1. Developer Tools   ->  console
![image](https://github.com/mbehr1/vsc-webshark/assets/103475252/0a4177df-3309-47bd-b56d-e5191495224a)
2. `sharkd.exe -` Looks fine.
![image](https://github.com/mbehr1/vsc-webshark/assets/103475252/8abd5f4e-0d5f-436b-98fe-4622840f897c)

**Comment by mbehr1** [comment]
@actanta which version of the extension are you using?

**Comment by hababy** [comment]
Attempt to modify the src code，windows11,  Sharkd (Wireshark) 4.2.6 (v4.2.6-0-g2acd1a854bab).
1.
this._proc = spawn(sharkdPath, spawnArgs);
![image](https://github.com/user-attachments/assets/5e7a3384-696e-4038-9891-7b66a3b9bcc7)
2.
![image](https://github.com/user-attachments/assets/4e3a1fc3-4e08-4a58-a68f-60898d46881c)
 
Then the plugin works
![image](https://github.com/user-attachments/assets/fb5f661d-b80b-470c-a177-2afb9b0344c3)

**Comment by mbehr1** [comment]
hmm. interesting.
So you did 3 changes:
a) removing the stdio:['pipe', 'pipe', 'pipe']] from spawn options
b) removing shell:true
c) setting loadReq['prevFrame'] to 1 instead of false

Can you tell whether really all 3 are necessary?
So if you e.g. add a) does it still work? (then same for b) and c))

**Comment by mbehr1** [comment]
According to node.js spec e.g. a) should anyhow be the default value (so removing it should be fine per se but it should help to fix the issue ;-) https://nodejs.org/docs/latest-v20.x/api/child_process.html#optionsstdio

**Comment by mbehr1** [comment]
For c) this is interesting as well.
The wireshark wiki doesn't help a lot: https://wiki.wireshark.org/sharkd-JSON-RPC-Request-Syntax#frame
Checking the wireshark/sharkd source from 4.0. branch "prev_frame" is defined as:
https://gitlab.com/wireshark/wireshark/-/blame/release-4.0/sharkd_session.c#L396
```
 {"frame",      "prev_frame", 2, JSMN_PRIMITIVE,    SHARKD_JSON_BOOLEAN,  OPTIONAL},
```

Can you try whether c) still works if you change it to true instead of 1? (this would at least fit to the SHARKD_JSON_BOOLEAN definition.)

**Comment by mbehr1** [comment]
Ah. now I understand: you do use wireshark 4.2 (not 4.0..).
There is was actually changed: https://gitlab.com/wireshark/wireshark/-/blob/release-4.2/sharkd_session.c#L406
```
 {"frame",      "prev_frame", 2, JSMN_PRIMITIVE,    SHARKD_JSON_UINTEGER, SHARKD_OPTIONAL},
// commented as  *   (o) prev_frame - previously displayed frame number
```
So yes, c) seems needed to wireshark 4.2 (need to check when the version was added and change semantics depending on the version). Will do this as a PR.

Would still be nice if a) and b) are really necessary to fix your issue.

**Comment by mbehr1** [comment]
@hababy  see above. could you check my questions? thx!

**Comment by hababy** [comment]
b)

**Comment by hababy** [comment]
b)

**Comment by hababy** [comment]
@mbehr1 b) save  shell:true
![image](https://github.com/user-attachments/assets/5673bf52-48a6-4474-822e-a637f34ea7cd)
a) No abnormalities，You're right

**Comment by mbehr1** [comment]
@hababy I fixed this in v2.1.1. Can you check? Works for me on mac with wireshark v4.0.10, v4.2.7 and v4.4.0.

**Comment by hababy** [comment]
> @hababy I fixed this in v2.1.1. Can you check? Works for me on mac with wireshark v4.0.10, v4.2.7 and v4.4.0.

Sharkd (Wireshark) 4.4.0 (v4.4.0-0-g009a163470b5) Windows11, Unable to work in v2.1.1 or V2.2.0;

When I block 'shell: true', it can work

**Comment by mbehr1** [comment]
ok. will take a look at the shell:true today

**Comment by mbehr1** [comment]
@hababy  can you help me with debugging. I cannot reproduce it (but I admit I have no win11 machine... only win10).
Could you change that line:
```
console.log(`SharkdProcess(${this.id}) closed with: ${code}`);
```
to output additionally 
```
data='${this._notReadyErrData}, partResp='${this._partialResponse?.toString()}'
```
thx!

**Comment by mbehr1** [comment]
and can you print your ```%COMSPEC%``` env variable?

**Comment by mbehr1** [comment]
I can reproduce it on a freshly installed win11 arm in a vm on a mac :-)

If wireshark/sharkd is installed in a path with a ' ' (space) then it does not work.
E.g. using as sharkd full path (on a german language win11)
```
c:\Programme\Wireshark\sharkd.exe
```
works but
```
c:\Program Files\Wireshark\sharkd.exe
```
does not work.
I'll try to find a fix for that.

**Comment by mbehr1** [comment]
Found a way which seems best fitting to the nodes child_process.spawn api:
spawn expects the command as first argument (and somewhat not the command with full path).
So I'll split the fullPath to the dir/base and use the dir as options.cwd and the base as command.

**Comment by hababy** [comment]
> %COMSPEC%

C:\Windows\system32\cmd.exe

**Comment by hababy** [comment]
> I can reproduce it on a freshly installed win11 arm in a vm on a mac :-)
> 
> If wireshark/sharkd is installed in a path with a ' ' (space) then it does not work. E.g. using as sharkd full path (on a german language win11)
> 
> ```
> c:\Programme\Wireshark\sharkd.exe
> ```
> 
> works but
> 
> ```
> c:\Program Files\Wireshark\sharkd.exe
> ```
> 
> does not work. I'll try to find a fix for that.

That's true，I can use it normally when using “D:\Wireshark\sharkd.exe”  instead of “D:\Program Files\Wireshark\sharkd.exe”

mklink /D "D:\Wireshark" "D:\Program Files\Wireshark\",  

![image](https://github.com/user-attachments/assets/109b09a2-a9c9-4b60-9e0b-6240a3c6f05e)
![image](https://github.com/user-attachments/assets/3d8d3ff1-3729-4290-a0c9-2679de385a02)

**Comment by mbehr1** [comment]
@hababy does version 2.2.1 fixes the issue?

**Comment by hababy** [comment]
version 2.2.1 fixes the issue @mbehr1 
![image](https://github.com/user-attachments/assets/ebaf0ba9-1996-434b-8621-94bc4b8c7b47)
![image](https://github.com/user-attachments/assets/0b8d7db2-e961-4557-b188-b60f71602c23)
![Uploading image.png…]()
