### ISSUE TITLE
Time format options

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [mbehr1/vsc-webshark#43]
Firstly, thank you for this extension!

Can I configure the "Time" column to display "Time-of-Day", instead of "Elapsed-Time"? This would allow me to match it up with other events occuring on the system.

By way of comparison, Wireshark supports a lot of time-display-format options:

![image](https://github.com/user-attachments/assets/5643151a-462d-42b5-90bb-5dab8893ea53)

Currently, I see vsc-webhark shows the "Time" column displayed as elapsed-time from "first-packet" or elapsed-time from a "reference-packet".

**Comment by mbehr1** [comment]
I’ll have a look!Am 07.08.2024 um 09:32 schrieb Matt Muggeridge ***@***.***>:﻿
Firstly, thank you for this extension!
Can I configure the "Time" column to display "Time-of-Day", instead of "Elapsed-Time"? This would allow me to match it up with other events occuring on the system.
By way of comparison, Wireshark supports a lot of time-display-format options:
image.png (view on web)
Currently, I see vsc-webhark shows the "Time" column displayed as elapsed-time from "first-packet" or elapsed-time from a "reference-packet".

**Comment by mbehr1** [comment]
Hello @LiveFreeAndRoam! Changing the columns/time-format is already supported.
E.g. you can use the following settings:
("Time" changed from "%t" to "%Yt" and added column width for "%Yt")
```
"vsc-webshark.columns": [
        {
            "No.": "%m"
        },
        {
            "Time": "%Yt"
        },
        {
            "Source": "%s"
        },
        {
            "Destination": "%d"
        },
        {
            "Protocol": "%p"
        },
        {
            "Length": "%L"
        },
        {
            "Info": "%i"
        }
    ],
    "vsc-webshark.columnsWidths": {
        "%m": 100,
        "%t": 119,
        "%Yt": 200,
        "%s": 262,
        "%d": 262,
        "%p": 95,
        "%L": 82
    },
```
See e.g. here for the possible values for columns: https://wiki.wireshark.org/sharkd-Info-Request-Output-Example

Does this help?

**Comment by mbehr1** [comment]
Time of day should most likely be: %At
```
"name": "Absolute time",
"format": "%At"
```

**Comment by LiveFreeAndRoam** [comment]
I think that would work and was eager to try it out, but now I cannot get vsc-webshark to display anything.  I checked my settings, and they seem ok.

Should I open a spearate issue?  This is the error I get:

```
2024-09-09 00:29:12.877 [error] TypeError: Cannot read properties of undefined (reading 'num')
	at Object.cb (/home/tester/.vscode-server/extensions/mbehr1.vsc-webshark-2.1.0/out/websharkView.js:516:107)
	at WebsharkView._sharkd2._onDataFunction (/home/tester/.vscode-server/extensions/mbehr1.vsc-webshark-2.1.0/out/websharkView.js:468:28)
	at Socket.<anonymous> (/home/tester/.vscode-server/extensions/mbehr1.vsc-webshark-2.1.0/out/websharkView.js:136:26)
	at Socket.emit (node:events:519:28)
	at addChunk (node:internal/streams/readable:559:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)

```

**Comment by mbehr1** [comment]
which wireshark version? if >4.0 you do need to update to extension version 2.1.1. 

Windows/mac/linux?

**Comment by LiveFreeAndRoam** [comment]
I had to upgrade Wireshark to use vsc-webshark.  This is what I have:
```
$ wireshark --version
Wireshark 4.2.6 (Git commit fca52ffc018f).
```

I then saw that vsc-webshark wanted to upgrade to 2.2.0.  I did that and reloaded the window, but get the same error with 2.2.0.

```
2024-09-09 02:31:16.119 [error] TypeError: Cannot read properties of undefined (reading 'num')
	at Object.cb (/home/tester/.vscode-server/extensions/mbehr1.vsc-webshark-2.2.0/out/websharkView.js:517:107)
	at WebsharkView._sharkd2._onDataFunction (/home/tester/.vscode-server/extensions/mbehr1.vsc-webshark-2.2.0/out/websharkView.js:469:28)
	at Socket.<anonymous> (/home/tester/.vscode-server/extensions/mbehr1.vsc-webshark-2.2.0/out/websharkView.js:137:26)
	at Socket.emit (node:events:519:28)
	at addChunk (node:internal/streams/readable:559:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)
```

**Comment by LiveFreeAndRoam** [comment]
Oh, this is a Linux server.  I'm using remote-SSH from my Windows machine.

**Comment by LiveFreeAndRoam** [comment]
Hold on, I may have found the problem...

**Comment by LiveFreeAndRoam** [comment]
Nope, sorry. That was a false alarm.  I thought I had the wrong "Full Path" configured, but it was fine.

**Comment by mbehr1** [comment]
@LiveFreeAndRoam  could you do a quick retest with new 2.2.1?
(not supposed to fix it but adds slightly better logging)

**Comment by mbehr1** [comment]
problem seems to be from here:
```
console.log(`WebsharkView sharkd2 'frames' got frame #${result[0].num} res=${JSON.stringify(result).slice(0, 200)}`);
```
result[0] is undefined. I'll add some checks around to log the result to easy debugging.

**Comment by mbehr1** [comment]
@LiveFreeAndRoam can you rerun with v2.2.2 and check for error logs? Thx!

**Comment by LiveFreeAndRoam** [comment]
Thank you @mbehr1.

I installed 2.2.2 and it's working again. I'm not sure it matters, but 5 days ago I also updated VSC to 1.93.1.

I'll keep an eye out for further problems.

**Comment by LiveFreeAndRoam** [comment]
I just tried opening a different file and the display was blank.  Also, I could not see any errors in the various OUTPUT terminals.

It seems it is related to the format of the file.  I have attached a zip with two files.  One it works with, the other it displays blank. I'm hoping this will help isolate the cause of the blank output.

[vsc-webshark-pcaps.zip](https://github.com/user-attachments/files/17021567/vsc-webshark-pcaps.zip)

**Comment by mbehr1** [comment]
@LiveFreeAndRoam thx for the files. The "fail.pcapng" has no frames (size just 60 bytes, wireshark 4.0 doesn't show any frame either).
So with the change from 2.2.2 where I handle the case where at least one frame was expected (the first frame in the file) this can now be opened.
If you have a wireshark version that shows a frame for that file please let me know.

I can close that issue, right?

**Comment by LiveFreeAndRoam** [comment]
Oh sheesh.  For all the hundreds of PCAPs I could have clicked on, I chose an empty one.

Sorry about that. Yes, please close this report.

I've now confirmed the vsc-webshark.columns and .columnWidths works nicely.

Thanks again for your efforts here. Being able to scan through my PCAPs within VSC is so much quicker and more convenient than loading them into Wireshark.
