### ISSUE TITLE
Configurable column settings which can duplicate wireshark column settings

### ISSUE THREAD

**Issue by VaibhavKanojia** [mbehr1/vsc-webshark#6]
Hello, as discussed 
is it possible to configure same column settings from wireshark in webshark plugin?
since im not using "length" and "no" columns and added "delta" column in wireshark column 
hence the data is shifted right by 1 column when viewed in webshark plugin

**Comment by mbehr1** [comment]
@VaibhavKanojia see release 1.6.0. If it works for you please comment and close this issue.

**Comment by VaibhavKanojia** [comment]
@mbehr1 Thanks! Works as expected
